setup-sshd: improve openssh configuration
Add a '?' option for help

Add magic keywords 'al|gh|gl <user>' to suggest gitlab.alpinelinux.org,
github.com or gitlab.com URL to user's key. This is to conveniently
fetch ssh keys without needing to type long URLs.

diff --git a/setup-sshd.in b/setup-sshd.in
--- a/setup-sshd.in
+++ b/setup-sshd.in
@@ -17,6 +17,22 @@ usage() {
 	exit $1
 }
 
+root_login_help() {
+	cat <<-__EOF__
+Valid options are:
+
+  yes                root will be able to login with password or ssh key
+
+  no                 root will not be allowed to login with ssh
+
+  prohibit-password  root will be able to login with ssh key but not with
+                     password
+
+  KEYURL             ssh key will be feetched from the KEYURL and added to
+                     /root/.ssh/authorized_keys
+__EOF__
+}
+
 authorized_key="$SSH_KEY"
 while getopts "hc:k:" opt; do
 	case $opt in
@@ -51,9 +67,26 @@ fi
 $MOCK apk add --quiet $pkgs
 
 if [ "$sshdchoice" = "openssh" ] && [ -z "$authorized_key" ]; then
+	suggest=prohibit-password
 	while true; do
-		ask "Allow root ssh login? ('yes', 'no', 'prohibit-password' or KEYURL)" prohibit-password
+		ask "Allow root ssh login? ('?' for help)" "$suggest"
 		case "$resp" in
+			'?')
+				root_login_help
+				continue
+				;;
+			"al "*)
+				suggest="https://gitlab.alpinelinux.org/${resp#* }.keys"
+				continue
+				;;
+			"gl "*)
+				suggest="https://gitlab.com/${resp#* }.keys"
+				continue
+				;;
+			"gh "*)
+				suggest="https://github.com/${resp#* }.keys"
+				continue
+				;;
 			yes|no|prohibit-password)
 				sed -i -E -e "s/^#?\s*PermitRootLogin.*/PermitRootLogin $resp/" "$ROOT"/etc/ssh/sshd_config
 				if ! grep -q ^PermitRootLogin "$ROOT"/etc/ssh/sshd_config; then
@@ -62,7 +95,10 @@ if [ "$sshdchoice" = "openssh" ] && [ -z "$authorized_key" ]; then
 				break
 				;;
 			http://*|https://*)
-				authorized_key="$(wget -qO- "$resp")" || { echo "Failed to fetch key from '$resp'"; continue; }
+				authorized_key="$(wget -qO- "$resp")" || {
+					echo "Failed to fetch key from '$resp'"
+					continue
+				}
 				break
 				;;
 		esac
