setup-timezone: exit with 1 if failed to install tzdata

diff --git a/setup-timezone.in b/setup-timezone.in
--- a/setup-timezone.in
+++ b/setup-timezone.in
@@ -89,7 +89,7 @@ else
 	apkdel=".setup-timezone"
 fi
 
-$MOCK apk add --quiet $pkg
+$MOCK apk add --quiet $pkg || die "Failed to install tzdata package"
 
 if [ -n "$apkdel" ]; then
 	trap "$MOCK apk del --quiet $apkdel" EXIT HUP INT TERM
