setup-sshd: mock fetching ssh key
and improve error message a bit

diff --git a/setup-sshd.in b/setup-sshd.in
--- a/setup-sshd.in
+++ b/setup-sshd.in
@@ -49,7 +49,7 @@ fi
 
 $MOCK apk add --quiet $pkgs
 
-if [ "$sshdchoice" = "openssh" ] && [ -z "authorized_keys" ]; then
+if [ "$sshdchoice" = "openssh" ] && [ -z "$authorized_key" ]; then
 	while true; do
 		ask "Allow root ssh login? ('yes', 'no', 'prohibit-password' or KEYURL) [prohibit-password]" prohibit-password
 		case "$resp" in
@@ -61,7 +61,7 @@ if [ "$sshdchoice" = "openssh" ] && [ -z "authorized_keys" ]; then
 				break
 				;;
 			http://*|https://*)
-				authorized_key="$($MOCK wget -qO- "$resp")" || { echo "Could not fetch key from '$resp'"; continue; }
+				authorized_key="$($MOCK wget -qO- "$resp")" || { echo "Failed to fetch key from '$resp'"; continue; }
 				break
 				;;
 		esac
@@ -84,7 +84,7 @@ if [ -n "$authorized_key" -a "$authorized_key" != "none" ]; then
 	case "$authorized_key" in
 		http*://*|ftp://)
 			key_url="$authorized_key"
-			authorized_key="$(wget -qO- "$key_url")" || die "Could not fetch key from '$key_url'"
+			authorized_key="$($MOCK wget -qO- "$key_url")" || die "Failed to fetch key from '$key_url'"
 			;;
 	esac
 	mkdir -p ${ROOT}/root/.ssh
