require root to run setup-alpine-web

diff --git a/setup-alpine-web.in b/setup-alpine-web.in
--- a/setup-alpine-web.in
+++ b/setup-alpine-web.in
@@ -123,6 +123,12 @@ EOF
 	exit 0
 }
 
+# require root
+if [ "$(id -u)" != "0" ]; then
+	echo "ERROR: This script must be run as root" 1>&2
+	exit 1
+fi
+
 # parse args
 while getopts "b:c:d:H:hR:" opts; do
 	case "$opts" in
