setup-interfaces: import wifi config from answerfile
fixes https://gitlab.alpinelinux.org/alpine/alpine-conf/-/work_items/10630

diff --git a/setup-interfaces.in b/setup-interfaces.in
--- a/setup-interfaces.in
+++ b/setup-interfaces.in
@@ -426,7 +426,7 @@ config_vlan() {
 
 usage() {
 	cat <<-__EOF__
-		usage: setup-interfaces [-abhir] [-p ROOT]
+		usage: setup-interfaces [-abhir] [-p ROOT] [-w FILE]
 
 		Setup network interfaces
 
@@ -437,6 +437,7 @@ usage() {
 		 -i  Read new contents of ${ROOT}etc/network/interfaces from stdin
 		 -p  Set the system root to operate in
 		 -r  Restart the networking service after the setup
+		 -w  Import FILE as ${ROOT}etc/wpa_supplicant/wpa_supplicant.conf
 	__EOF__
 	exit $1
 }
@@ -608,10 +609,23 @@ auto_setup() {
 	EOF
 }
 
+import_wifi_config() {
+	local wifiopts="$1"
+	local conffile="$ROOT"/etc/wpa_supplicant/wpa_supplicant.conf
+
+	[ -n "$wifiopts" ] || return 0
+	[ -f "$wifiopts" ] || die "$wifiopts: wpa_supplicant config not found"
+
+	apk add --quiet --no-progress wpa_supplicant
+	rc-update --quiet add wpa_supplicant boot
+	mkdir -p "${conffile%/*}"
+	cp -f "$wifiopts" "$conffile"
+}
+
 ask_bridge=
 is_xen_dom0 && ask_bridge=1
 
-while getopts "abhip:r" opt; do
+while getopts "abhip:rw:" opt; do
 	case $opt in
 		a) auto=1;;
 		b) ask_bridge=1;;
@@ -619,6 +633,7 @@ while getopts "abhip:r" opt; do
 		i) STDINPUT=1;;
 		p) ROOT=$OPTARG;;
 		r) restart=1;;
+		w) WIFIOPTS=$OPTARG;;
 		'?') usage "1" >&2;;
 	esac
 done
@@ -635,6 +650,8 @@ elif [ -n "$auto" ]; then
 else
 	prompt_for_interfaces
 fi
+
+import_wifi_config "$WIFIOPTS"
 
 if [ -n "$restart" ]; then
 	rc-service networking --quiet restart >/dev/null
